version: "3.8" 
services:
  app:
    build:
      context: .
    volumes:
      - .:/REACT-TUTORIAL
    ports:
      - 3000:3000
    image: react-frontend
    container_name: react-frontend
    command: npm start
    networks:
      - spring-net

networks:
  spring-net:
    external: true